typography_spectrum: 0.37836370756849647
color:
  brandStrength: 0.8213382959365845
  lightness: 0.7712255781516433
  saturation: 0.4122623326256871
  rhythmicContrast: 0.2953768391162157
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.16657137777656317
name: Baldwin80
title: Baldwin80
description: Alumni
